# Generated by Django 5.1.6 on 2025-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=25)),
                ('grade_level', models.CharField(max_length=25)),
                ('strand', models.CharField(max_length=50)),
                ('internet_access', models.JSONField(help_text='List of selected internet access types')),
                ('devices', models.JSONField(help_text='List of owned digital devices')),
                ('screen_time', models.CharField(max_length=25)),
                ('pre_sleep_use', models.CharField(max_length=50)),
                ('usage_purpose', models.JSONField(help_text='List of selected purposes')),
                ('device_check_freq', models.PositiveSmallIntegerField()),
                ('usage_interrupts_tasks', models.PositiveSmallIntegerField()),
                ('control_level', models.PositiveSmallIntegerField()),
                ('study_distraction', models.PositiveSmallIntegerField()),
                ('wakeup_use', models.BooleanField()),
                ('num_socials', models.PositiveSmallIntegerField()),
                ('attempted_detox', models.BooleanField()),
                ('aware_of_hours', models.BooleanField()),
                ('time_of_day_use', models.CharField(max_length=50)),
                ('sleep_disrupted', models.BooleanField()),
                ('predicted_qol', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
